from __future__ import annotations

from pathlib import Path


def write_comparison_page(path: Path) -> None:
    path.write_text(_HTML, encoding="utf-8")


_HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>PISA Concrete Scenario Comparison</title>
  <style>
    :root { --navy:#102033; --ink:#17202a; --muted:#64748b; --line:#d9e1ea; --bg:#f4f7fa; --paper:#fff; --red:#dc2626; --orange:#f59e0b; }
    * { box-sizing:border-box; } body { margin:0; font-family:Inter,system-ui,sans-serif; color:var(--ink); background:var(--bg); }
    header { background:var(--navy); color:white; padding:18px 26px; display:flex; align-items:center; gap:18px; }
    header h1 { margin:0; font-size:22px; } header a { color:#dbeafe; }
    main { padding:16px 24px 48px; max-width:1800px; margin:auto; }
    .toolbar,.grid,.summary-grid { display:grid; gap:12px; } .toolbar { grid-template-columns:2fr 1fr 1fr; position:sticky; top:0; z-index:3; background:#eef4f9; border:1px solid var(--line); border-radius:8px; padding:10px; }
    .grid { grid-template-columns:280px minmax(0,1fr); align-items:start; margin-top:12px; }
    .summary-grid { grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); }
    section,.panel { background:var(--paper); border:1px solid var(--line); border-radius:8px; padding:14px; margin-bottom:12px; min-width:0; }
    h2 { margin:0 0 10px; font-size:18px; } h3 { margin:14px 0 8px; font-size:14px; }
    label { display:grid; gap:4px; font-size:12px; font-weight:700; color:#314155; }
    select,input,button { min-height:34px; padding:6px 8px; border:1px solid #aab7c4; border-radius:6px; background:white; }
    button { cursor:pointer; background:var(--navy); color:white; border-color:var(--navy); }
    button.secondary { background:white; color:var(--ink); border-color:#aab7c4; }
    .checks { display:grid; gap:7px; max-height:330px; overflow:auto; } .checks label { display:flex; align-items:flex-start; gap:7px; font-weight:500; }
    .swatch { width:12px; height:12px; margin-top:3px; border-radius:2px; flex:none; }
    canvas { display:block; width:100%; height:520px; background:white; border:1px solid var(--line); border-radius:6px; }
    #metric-canvas,#control-canvas { height:340px; } .inline { display:flex; flex-wrap:wrap; gap:8px; align-items:end; margin-bottom:10px; } .inline label { min-width:150px; }
    .series-grid,.results-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px; }
    .results { grid-column:1/-1; }
    .playback { display:grid; grid-template-columns:auto auto 1fr; gap:6px; margin:8px 0; }
    .playback button { min-width:40px; font-size:16px; }
    table { border-collapse:collapse; width:100%; font-size:12px; display:block; overflow:auto; max-height:430px; }
    th,td { padding:7px 8px; border-bottom:1px solid #e5e7eb; text-align:left; white-space:nowrap; }
    .muted { color:var(--muted); } .warning { color:#b45309; } .bad { color:#b91c1c; font-weight:700; }
    .config-label { line-height:1.25; } .config-meta { color:var(--muted); font-size:11px; }
    .card { border:1px solid var(--line); border-radius:7px; padding:10px; } .card b { display:block; font-size:19px; margin-top:3px; }
    #load-error { display:none; background:#fef2f2; border-left:4px solid var(--red); padding:10px; }
    @media(max-width:1200px) { .grid,.series-grid,.results-grid { grid-template-columns:1fr; } .toolbar { grid-template-columns:1fr; position:relative; } }
  </style>
</head>
<body>
<header><a href="analysis_report.html">Back to report</a><h1>Concrete Scenario Comparison</h1></header>
<main>
  <div class="toolbar">
    <label>Search concrete scenario<input id="group-search" placeholder="sample id, parameter, outcome, config"></label>
    <label>Scenario<select id="group-select"></select></label>
    <label>Baseline<select id="baseline-select"></select></label>
  </div>
  <p id="load-error"></p>
  <section><h2 id="group-title">Select a concrete scenario</h2><div id="params" class="muted"></div><div id="summary-cards" class="summary-grid"></div></section>
  <div class="grid">
    <aside>
      <section><h2>Configs</h2><div class="inline"><button id="adaptive" type="button">Adaptive</button><button id="all" class="secondary" type="button">All</button><button id="disagreements" class="secondary" type="button">Disagreements</button></div><div id="config-checks" class="checks"></div></section>
      <section><h2>Actors</h2><div id="actor-checks" class="checks"></div></section>
      <section><h2>Time</h2><div class="playback"><button id="play" type="button" title="Play or pause">▶</button><button id="restart" class="secondary" type="button" title="Restart">↺</button><label>Speed<select id="playback-speed"><option value="0.5">0.5x</option><option value="1" selected>1x</option><option value="2">2x</option></select></label></div><input id="time-slider" type="range" min="0" max="0" step="1" value="0" style="width:100%"><div id="time-label" class="muted"></div><label><span><input id="trail-only" type="checkbox"> Show path only to cursor</span></label></section>
    </aside>
    <div>
      <section><h2>Trajectory Overlay</h2><canvas id="trajectory-canvas"></canvas><div class="muted">Equal XY scale. Config is encoded by color; actor is encoded by line pattern.</div></section>
      <div class="series-grid"><section><h2>Metrics</h2><div class="inline"><label>Field<select id="metric-field"></select></label><label>Scale<select id="metric-scale"><option value="semantic">Semantic</option><option value="detail">Detail</option></select></label></div><canvas id="metric-canvas"></canvas><div id="metric-info" class="muted"></div></section><section><h2>Controls</h2><div class="inline"><label>Field<select id="control-field"></select></label><label>Scale<select id="control-scale"><option value="semantic">Semantic</option><option value="detail">Detail</option></select></label></div><canvas id="control-canvas"></canvas><div id="control-info" class="muted"></div></section></div>
    </div>
    <div class="results"><div class="results-grid"><section><h2>Config Results</h2><div id="config-table"></div></section><section><h2>Trajectory Differences</h2><div id="trajectory-table"></div></section><section><h2>Metric Differences</h2><div id="metric-table"></div></section><section><h2>Control Differences</h2><div id="control-table"></div></section><section><h2>Difference Timeline</h2><div id="timeline-table"></div></section><section><h2>Data Quality</h2><div id="warnings"></div></section></div></div>
  </div>
</main>
<script src="comparison_index.js"></script>
<script>
(() => {
  const index = window.PISA_COMPARISON_INDEX?.groups || [];
  const chunks = window.PISA_COMPARISON_CHUNKS = window.PISA_COMPARISON_CHUNKS || {};
  const palette = ['#2563eb','#dc2626','#16a34a','#f59e0b','#7c3aed','#0891b2','#be123c','#4b5563','#84cc16','#ea580c','#0f766e','#c026d3'];
  const state = {group:null, selected:new Set(), actors:new Set(), baseline:null, timeline:[], timeIndex:0, time:null, playing:false, timer:null};
  const el = id => document.getElementById(id), tctx=el('trajectory-canvas').getContext('2d'), mctx=el('metric-canvas').getContext('2d'), cctx=el('control-canvas').getContext('2d');
  const esc = value => String(value ?? '').replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[ch]));
  const fmt = value => Number.isFinite(Number(value)) ? Number(Number(value).toPrecision(4)).toString() : String(value ?? '');
  function color(id) { let hash=0; for(const ch of id) hash=(hash*31+ch.charCodeAt(0))>>>0; return palette[hash%palette.length]; }
  function table(rows) { if(!rows.length) return '<p class="muted">No comparable data.</p>'; const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))]; return '<table><thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(typeof r[c]==='number'?fmt(r[c]):r[c])}</td>`).join('')+'</tr>').join('')+'</tbody></table>'; }
  function initIndex() { el('group-select').textContent=''; index.forEach(item=>el('group-select').appendChild(new Option(`${item.logical_scenario_name} | ${JSON.stringify(item.params)} | ${item.configs.length} configs`,item.group_id))); const requested=new URLSearchParams(location.search).get('group'); if(requested && index.some(item=>item.group_id===requested)) el('group-select').value=requested; filterGroups(); loadSelected(); }
  function filterGroups() { const q=el('group-search').value.toLowerCase(); [...el('group-select').options].forEach((option,i)=>option.hidden=!!q && !index[i].search_text.includes(q)); }
  function loadSelected() { const id=el('group-select').value, entry=index.find(item=>item.group_id===id); if(!entry) return; history.replaceState(null,'',`?group=${encodeURIComponent(id)}`); if(chunks[id]) return useChunk(chunks[id]); const script=document.createElement('script'); script.src=entry.chunk; script.onload=()=>useChunk(chunks[id]); script.onerror=()=>showError(`Could not load ${entry.chunk}`); document.head.appendChild(script); }
  function showError(message) { el('load-error').style.display='block'; el('load-error').textContent=message; }
  function useChunk(chunk) { pause();el('load-error').style.display='none'; state.group=chunk; state.baseline=chunk.configs[0]?.config_id || null; adaptiveSelection(); populateBaseline(); populateActors(); populateFields('metrics');populateFields('controls'); renderAll(); }
  function adaptiveSelection() { const configs=state.group.configs, baseline=configs[0]; state.selected=new Set(); if(configs.length<=6) configs.forEach(c=>state.selected.add(c.config_id)); else { state.selected.add(baseline.config_id); configs.filter(c=>c.outcome!==baseline.outcome).forEach(c=>state.selected.add(c.config_id)); if(state.selected.size===1) configs.slice(1,5).forEach(c=>state.selected.add(c.config_id)); } renderConfigChecks(); }
  function selectAll() { pause();state.group.configs.forEach(c=>state.selected.add(c.config_id));renderConfigChecks();populateActors();populateFields('metrics');populateFields('controls');renderAll(); }
  function selectDisagreements() { pause();const base=state.group.configs.find(c=>c.config_id===state.baseline);state.selected=new Set([state.baseline]);state.group.configs.filter(c=>c.outcome!==base.outcome).forEach(c=>state.selected.add(c.config_id));renderConfigChecks();populateActors();populateFields('metrics');populateFields('controls');renderAll(); }
  function populateBaseline() { const select=el('baseline-select'); select.textContent=''; state.group.configs.forEach(c=>select.appendChild(new Option(c.label,c.config_id))); select.value=state.baseline; }
  function renderConfigChecks() { const box=el('config-checks'); box.textContent=''; state.group.configs.forEach(config=>{ const label=document.createElement('label'), input=document.createElement('input'), swatch=document.createElement('span'), text=document.createElement('span'); input.type='checkbox'; input.checked=state.selected.has(config.config_id); input.addEventListener('change',()=>{ pause();input.checked?state.selected.add(config.config_id):state.selected.delete(config.config_id); if(!state.selected.has(state.baseline) && state.selected.size) { state.baseline=[...state.selected][0]; populateBaseline(); } populateActors(); populateFields('metrics');populateFields('controls');renderAll(); }); swatch.className='swatch'; swatch.style.background=color(config.config_id); text.innerHTML=`<span class="config-label">${esc(config.label)}</span><br><span class="config-meta">${esc(config.outcome)} · sample ${esc(config.sample_id)}</span>`; label.append(input,swatch,text); box.appendChild(label); }); }
  function selectedConfigs() { return state.group.configs.filter(c=>state.selected.has(c.config_id)); }
  function populateActors() { const configs=selectedConfigs(); const actorSets=configs.map(c=>new Set(c.trajectory.map(a=>a.agent_id))); const common=actorSets.length?[...actorSets[0]].filter(id=>actorSets.every(set=>set.has(id))):[]; const ego=new Set(configs.flatMap(c=>c.trajectory.filter(a=>a.is_ego).map(a=>a.agent_id))); state.actors=new Set([...ego,...common]); const box=el('actor-checks'); box.textContent=''; [...new Set(configs.flatMap(c=>c.trajectory.map(a=>a.agent_id)))].sort().forEach(id=>{ const label=document.createElement('label'), input=document.createElement('input'); input.type='checkbox'; input.checked=state.actors.has(id); input.addEventListener('change',()=>{input.checked?state.actors.add(id):state.actors.delete(id); drawTrajectory();}); label.append(input,document.createTextNode(` actor ${id}${ego.has(id)?' (ego)':''}`)); box.appendChild(label); }); updateTimeRange(); }
  function populateFields(source) { const select=el(source==='metrics'?'metric-field':'control-field'),previous=select.value,fields=new Map(); selectedConfigs().flatMap(c=>c.series).filter(s=>s.source===source).forEach(s=>fields.set(s.field,s));select.textContent='';fields.forEach(item=>select.appendChild(new Option(`${item.label}${item.unit?' ('+item.unit+')':''}`,item.field)));if(fields.has(previous))select.value=previous; }
  function updateTimeRange() { const previous=state.time,times=new Set();selectedConfigs().forEach(config=>(config.timeline_s||[]).forEach(time=>times.add(Number(time))));state.timeline=[...times].filter(Number.isFinite).sort((a,b)=>a-b);if(!state.timeline.length)state.timeline=[0];state.timeIndex=previous===null?state.timeline.length-1:nearestTimeIndex(previous);setTimeIndex(state.timeIndex,false); }
  function nearestTimeIndex(time) { let best=0,distance=Infinity;state.timeline.forEach((value,index)=>{const candidate=Math.abs(value-time);if(candidate<distance){distance=candidate;best=index;}});return best; }
  function setTimeIndex(index,redraw=true) { state.timeIndex=Math.max(0,Math.min(state.timeline.length-1,Number(index)||0));state.time=state.timeline[state.timeIndex];el('time-slider').min=0;el('time-slider').max=Math.max(0,state.timeline.length-1);el('time-slider').step=1;el('time-slider').value=state.timeIndex;el('time-label').textContent=`Step ${state.timeIndex+1} / ${state.timeline.length} · ${fmt(state.time)} s`;if(redraw){drawTrajectory();drawSeries();} }
  function resizeCanvas(canvas,height) { const rect=canvas.getBoundingClientRect(); canvas.width=Math.max(720,Math.floor(rect.width))*devicePixelRatio; canvas.height=height*devicePixelRatio; }
  function drawTrajectory() { const canvas=el('trajectory-canvas'); resizeCanvas(canvas,520); const ctx=tctx,w=canvas.width,h=canvas.height,m=58*devicePixelRatio; ctx.fillStyle='white';ctx.fillRect(0,0,w,h); const configs=selectedConfigs(), paths=[]; configs.forEach(c=>c.trajectory.filter(a=>state.actors.has(a.agent_id)).forEach(a=>paths.push({config:c,actor:a,points:el('trail-only').checked?a.points.filter(p=>p[0]<=state.time):a.points}))); const all=paths.flatMap(p=>p.points); if(!all.length) return empty(ctx,'No common trajectory data.'); let xmin=Math.min(...all.map(p=>p[1])),xmax=Math.max(...all.map(p=>p[1])),ymin=Math.min(...all.map(p=>p[2])),ymax=Math.max(...all.map(p=>p[2])); if(xmin===xmax){xmin-=.5;xmax+=.5;} if(ymin===ymax){ymin-=.5;ymax+=.5;} const span=Math.max(xmax-xmin,ymax-ymin),xc=(xmin+xmax)/2,yc=(ymin+ymax)/2;xmin=xc-span/2;xmax=xc+span/2;ymin=yc-span/2;ymax=yc+span/2; const sx=x=>m+(x-xmin)/(xmax-xmin)*(w-2*m),sy=y=>h-m-(y-ymin)/(ymax-ymin)*(h-2*m); axes(ctx,w,h,m,xmin,xmax,ymin,ymax,'x (m)','y (m)'); paths.forEach(({config,actor,points})=>{if(!points.length)return;ctx.strokeStyle=color(config.config_id);ctx.lineWidth=(actor.is_ego?3:1.8)*devicePixelRatio;ctx.setLineDash(actor.is_ego?[]:[6*devicePixelRatio,4*devicePixelRatio]);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(sx(p[1]),sy(p[2])):ctx.moveTo(sx(p[1]),sy(p[2])));ctx.stroke();ctx.setLineDash([]);const marker=nearest(actor.points,state.time);if(marker){ctx.fillStyle=color(config.config_id);ctx.beginPath();ctx.arc(sx(marker[1]),sy(marker[2]),4*devicePixelRatio,0,Math.PI*2);ctx.fill();}});configs.forEach(config=>config.collisions.forEach(event=>{const x=Number(event.x),y=Number(event.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;ctx.strokeStyle=color(config.config_id);ctx.lineWidth=3*devicePixelRatio;ctx.beginPath();ctx.moveTo(sx(x)-6*devicePixelRatio,sy(y)-6*devicePixelRatio);ctx.lineTo(sx(x)+6*devicePixelRatio,sy(y)+6*devicePixelRatio);ctx.moveTo(sx(x)+6*devicePixelRatio,sy(y)-6*devicePixelRatio);ctx.lineTo(sx(x)-6*devicePixelRatio,sy(y)+6*devicePixelRatio);ctx.stroke();})); }
  function drawSeries() { drawSeriesPanel('metrics',mctx);drawSeriesPanel('controls',cctx); }
  function drawSeriesPanel(source,ctx) { const canvas=el(source==='metrics'?'metric-canvas':'control-canvas'),field=el(source==='metrics'?'metric-field':'control-field').value,scale=el(source==='metrics'?'metric-scale':'control-scale').value,info=el(source==='metrics'?'metric-info':'control-info');resizeCanvas(canvas,340);const w=canvas.width,h=canvas.height,m=58*devicePixelRatio;ctx.fillStyle='white';ctx.fillRect(0,0,w,h);const rows=selectedConfigs().map(config=>({config,item:config.series.find(series=>series.source===source&&series.field===field)})).filter(row=>row.item);if(!rows.length){info.textContent='No selected series data.';return empty(ctx,'No selected series data.');}const all=rows.flatMap(row=>row.item.points),xmin=Math.min(...all.map(point=>point[0])),xmax=Math.max(...all.map(point=>point[0]));let ymin,ymax;if(scale==='semantic'){ymin=Math.min(...rows.map(row=>row.item.semantic_limits.lower));ymax=Math.max(...rows.map(row=>row.item.semantic_limits.upper));}else{ymin=Math.min(...rows.map(row=>row.item.detail_limits.lower));ymax=Math.max(...rows.map(row=>row.item.detail_limits.upper));}const sx=x=>m+(x-xmin)/(xmax-xmin||1)*(w-2*m),sy=y=>h-m-(y-ymin)/(ymax-ymin||1)*(h-2*m);axes(ctx,w,h,m,xmin,xmax,ymin,ymax,'time (s)',rows[0].item.label);rows.forEach(({config,item})=>{ctx.strokeStyle=color(config.config_id);ctx.lineWidth=2*devicePixelRatio;ctx.beginPath();item.points.forEach((point,index)=>index?ctx.lineTo(sx(point[0]),sy(point[1])):ctx.moveTo(sx(point[0]),sy(point[1])));ctx.stroke();});if(state.time!==null){ctx.strokeStyle='#111827';ctx.setLineDash([4*devicePixelRatio,3*devicePixelRatio]);ctx.beginPath();ctx.moveTo(sx(state.time),m);ctx.lineTo(sx(state.time),h-m);ctx.stroke();ctx.setLineDash([]);}const values=rows.map(({config,item})=>`<span style="color:${color(config.config_id)}">${esc(config.label)}: ${fmt(valueAt(item.points,state.time,item.interpolation))}</span>`);info.innerHTML=`${fmt(ymin)} to ${fmt(ymax)}${rows[0].item.unit?' '+esc(rows[0].item.unit):''}<br>${values.join(' · ')}`; }
  function valueAt(points,time,interpolation) { if(!points.length)return null;if(time<=points[0][0])return points[0][1];for(let index=1;index<points.length;index++){if(time>points[index][0])continue;const left=points[index-1],right=points[index];if(interpolation==='previous'||right[0]===left[0])return left[1];return left[1]+(right[1]-left[1])*(time-left[0])/(right[0]-left[0]);}return points[points.length-1][1]; }
  function axes(ctx,w,h,m,xmin,xmax,ymin,ymax,xlabel,ylabel){ctx.strokeStyle='#cbd5e1';ctx.lineWidth=devicePixelRatio;ctx.beginPath();ctx.moveTo(m,m);ctx.lineTo(m,h-m);ctx.lineTo(w-m,h-m);ctx.stroke();ctx.fillStyle='#475569';ctx.font=`${11*devicePixelRatio}px system-ui`;ctx.textAlign='center';ctx.fillText(xlabel,w/2,h-14*devicePixelRatio);ctx.save();ctx.translate(16*devicePixelRatio,h/2);ctx.rotate(-Math.PI/2);ctx.fillText(ylabel,0,0);ctx.restore();ctx.textAlign='right';ctx.fillText(fmt(ymax),m-7*devicePixelRatio,m+4*devicePixelRatio);ctx.fillText(fmt(ymin),m-7*devicePixelRatio,h-m+4*devicePixelRatio);ctx.textAlign='center';ctx.fillText(fmt(xmin),m,h-m+18*devicePixelRatio);ctx.fillText(fmt(xmax),w-m,h-m+18*devicePixelRatio);if(ymin<=0&&ymax>=0){const y=h-m-(0-ymin)/(ymax-ymin||1)*(h-2*m);ctx.strokeStyle='#64748b';ctx.beginPath();ctx.moveTo(m,y);ctx.lineTo(w-m,y);ctx.stroke();}}
  function nearest(points,time){if(!points.length)return null;return points.reduce((best,p)=>Math.abs(p[0]-time)<Math.abs(best[0]-time)?p:best,points[0]);}
  function empty(ctx,message){ctx.fillStyle='#64748b';ctx.font=`${14*devicePixelRatio}px system-ui`;ctx.fillText(message,30*devicePixelRatio,45*devicePixelRatio);}
  function oriented(rows) { return rows.filter(r=>(r.left_config===state.baseline&&state.selected.has(r.right_config))||(r.right_config===state.baseline&&state.selected.has(r.left_config))).map(r=>{const reverse=r.right_config===state.baseline,other=reverse?r.left_config:r.right_config;return {...r,config:other,mean_delta:r.mean_delta===undefined?'':(reverse?-r.mean_delta:r.mean_delta),median_delta:r.median_delta===undefined?'':(reverse?-r.median_delta:r.median_delta)};}); }
  function renderTables(){const configs=selectedConfigs(),base=state.group.configs.find(c=>c.config_id===state.baseline);el('config-table').innerHTML=table(configs.map(c=>({config:c.label,outcome:c.outcome,termination:c.termination_reason||'',min_ttc:c.canonical_metrics.min_ttc,delta_min_ttc:delta(c.canonical_metrics.min_ttc,base?.canonical_metrics.min_ttc),min_distance:c.canonical_metrics.min_distance,delta_min_distance:delta(c.canonical_metrics.min_distance,base?.canonical_metrics.min_distance),warnings:c.warnings.length})));const traj=oriented(state.group.pairwise_trajectory).map(r=>({config:r.config,actor:r.agent_id,ADE:r.ade,FDE:r.fde,RMSE:r.rmse,max:r.max_error,first_divergence_s:r.first_divergence_s}));el('trajectory-table').innerHTML=table(traj);for(const source of ['metrics','controls']){const field=el(source==='metrics'?'metric-field':'control-field').value,series=oriented(state.group.pairwise_series).filter(r=>r.source===source&&r.field===field).map(r=>({config:r.config,field:r.field,mean_delta:r.mean_delta,median_delta:r.median_delta,max_abs:r.max_abs_delta,first_divergence_s:r.first_divergence_s}));el(source==='metrics'?'metric-table':'control-table').innerHTML=table(series);}const divergence=[...traj.filter(r=>r.first_divergence_s!==null).map(r=>({config:r.config,event:`trajectory actor ${r.actor}`,time_s:r.first_divergence_s})),...oriented(state.group.pairwise_series).filter(r=>r.first_divergence_s!==null).map(r=>({config:r.config,event:`${r.source}.${r.field}`,time_s:r.first_divergence_s}))],events=configs.flatMap(c=>[...c.events.map(e=>({config:c.config_id,event:e.event_type||e.event||e.name||'scenario event',time_s:Number(e.sim_time_ms)/1000})),...c.collisions.map(e=>({config:c.config_id,event:'collision',time_s:Number(e.sim_time_ms)/1000})),...(Number.isFinite(Number(c.metrics['run.final_sim_time_ms']))?[{config:c.config_id,event:`termination: ${c.termination_reason||'run end'}`,time_s:Number(c.metrics['run.final_sim_time_ms'])/1000}]:[])]).filter(e=>Number.isFinite(e.time_s));el('timeline-table').innerHTML=table([...divergence,...events].sort((a,b)=>a.time_s-b.time_s));const warnings=[...(state.group.group.warnings||[]).map(w=>`<div class="warning">${esc(w)}</div>`),...configs.flatMap(c=>c.warnings.map(w=>`<div class="warning">${esc(c.label)}: ${esc(w)}</div>`))];el('warnings').innerHTML=warnings.join('')||'<p class="muted">No automatic warnings.</p>';}
  function delta(value,baseline){const left=Number(value),right=Number(baseline);return Number.isFinite(left)&&Number.isFinite(right)?left-right:'';}
  function renderSummary(){const g=state.group.group;el('group-title').textContent=`${g.logical_scenario_name} · ${g.group_id}`;el('params').textContent=JSON.stringify(g.params);const configs=selectedConfigs(),outcomes=new Set(configs.map(c=>c.outcome));el('summary-cards').innerHTML=[['Selected configs',configs.length],['Available configs',state.group.configs.length],['Outcome classes',outcomes.size],['Pairing',g.pairing_method]].map(([k,v])=>`<div class="card">${k}<b>${v}</b></div>`).join('');}
  function renderAll(){renderSummary();drawTrajectory();drawSeries();renderTables();}
  function pause(){if(state.timer)clearTimeout(state.timer);state.timer=null;state.playing=false;el('play').textContent='▶';}
  function togglePlay(){if(state.playing)return pause();if(state.timeIndex>=state.timeline.length-1)setTimeIndex(0);state.playing=true;el('play').textContent='Ⅱ';scheduleNext();}
  function scheduleNext(){if(!state.playing)return;if(state.timeIndex>=state.timeline.length-1)return pause();const current=state.timeline[state.timeIndex],next=state.timeline[state.timeIndex+1],speed=Number(el('playback-speed').value)||1,delay=Math.max(0,(next-current)*1000/speed);state.timer=setTimeout(()=>{setTimeIndex(state.timeIndex+1);scheduleNext();},delay);}
  function restart(){pause();setTimeIndex(0);}
  function scrubSeries(event){const rect=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left)/(rect.width||1)));pause();setTimeIndex(Math.round(ratio*(state.timeline.length-1)));}
  el('group-search').addEventListener('input',filterGroups);el('group-select').addEventListener('change',loadSelected);el('baseline-select').addEventListener('change',()=>{pause();state.baseline=el('baseline-select').value;state.selected.add(state.baseline);renderConfigChecks();renderAll();});el('adaptive').addEventListener('click',()=>{pause();adaptiveSelection();populateActors();populateFields('metrics');populateFields('controls');renderAll();});el('all').addEventListener('click',selectAll);el('disagreements').addEventListener('click',selectDisagreements);for(const source of ['metrics','controls']){el(source==='metrics'?'metric-field':'control-field').addEventListener('change',()=>{drawSeries();renderTables();});el(source==='metrics'?'metric-scale':'control-scale').addEventListener('change',drawSeries);el(source==='metrics'?'metric-canvas':'control-canvas').addEventListener('mousemove',scrubSeries);}el('time-slider').addEventListener('input',()=>{pause();setTimeIndex(Number(el('time-slider').value));});el('play').addEventListener('click',togglePlay);el('restart').addEventListener('click',restart);el('playback-speed').addEventListener('change',()=>{if(state.playing){pause();togglePlay();}});el('trail-only').addEventListener('change',drawTrajectory);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('resize',renderAll);initIndex();
})();
</script>
</body></html>
"""
