"""Normalized, lazy report indexing and scientific comparison primitives."""

from .bundle import (
    REPORT_ARTIFACT_TYPE,
    REPORT_BUILD_VERSION,
    REPORT_MANIFEST_SCHEMA_VERSION,
    REPORT_TOOL,
    ReportBundleError,
    build_report_bundle,
    rebuild_legacy_report,
)
from .comparison import (
    NON_BEHAVIOR_RUNNER_SPEC_PATHS,
    classify_comparison,
    semantic_compatibility,
    semantic_projection,
    structured_diff,
)
from .discovery import ExperimentSource, discover_experiments, discovery_fingerprint
from .index import (
    REPORT_INDEX_BUILD_VERSION,
    REPORT_INDEX_SCHEMA_VERSION,
    ReportIndex,
    ReportIndexError,
    build_report_index,
)
from .models import (
    ComparisonAssessment,
    ComparisonRole,
    DataHealthFinding,
    DatasetDescriptor,
    DatasetRelation,
    FindingSeverity,
    IndexBuildResult,
    IndexedAttempt,
    IndexedRun,
    OutcomeSummary,
    ReportBundleResult,
    RunFilter,
    RunPage,
    SourceFingerprint,
    StageTiming,
)

__all__ = [
    "NON_BEHAVIOR_RUNNER_SPEC_PATHS",
    "REPORT_ARTIFACT_TYPE",
    "REPORT_BUILD_VERSION",
    "REPORT_INDEX_BUILD_VERSION",
    "REPORT_INDEX_SCHEMA_VERSION",
    "REPORT_MANIFEST_SCHEMA_VERSION",
    "REPORT_TOOL",
    "ComparisonAssessment",
    "ComparisonRole",
    "DataHealthFinding",
    "DatasetDescriptor",
    "DatasetRelation",
    "ExperimentSource",
    "FindingSeverity",
    "IndexBuildResult",
    "IndexedAttempt",
    "IndexedRun",
    "OutcomeSummary",
    "ReportBundleError",
    "ReportBundleResult",
    "ReportIndex",
    "ReportIndexError",
    "RunFilter",
    "RunPage",
    "SourceFingerprint",
    "StageTiming",
    "build_report_index",
    "build_report_bundle",
    "classify_comparison",
    "discover_experiments",
    "discovery_fingerprint",
    "semantic_compatibility",
    "semantic_projection",
    "rebuild_legacy_report",
    "structured_diff",
]
