from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from .formatters import format_table, format_yaml, result_to_dict
from .models import SamplerTestError
from .service import collect_sampler_preview


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="pisa-sample-test",
        description="Preview samples generated by a simcore sampler source file.",
    )
    parser.add_argument("source_file", type=Path)
    parser.add_argument(
        "--method",
        "--sampler",
        dest="method",
        default=None,
        help="Sampler method registered in simcore.sampler, e.g. native, grid, lhs, sobol, explicit.",
    )
    parser.add_argument(
        "--source-type",
        default=None,
        help="Source format. Defaults to simcore extension inference.",
    )
    parser.add_argument("--module-path", default=None, help="External sampler module path.")
    parser.add_argument("--config-path", type=Path, default=None, help="YAML/JSON sampler config.")
    parser.add_argument("--n-samples", type=int, default=None, help="Sample count for LHS/Sobol.")
    parser.add_argument("--seed", type=int, default=None, help="Random seed for LHS.")
    parser.add_argument("--skip", type=int, default=None, help="Initial Sobol points to skip.")
    parser.add_argument(
        "--max-samples", type=int, default=None, help="Print at most this many samples."
    )
    parser.add_argument(
        "--format",
        choices=["table", "yaml", "json"],
        default="table",
        help="Output format.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    config = sampler_config_from_args(args)
    try:
        result = collect_sampler_preview(
            source_file=args.source_file,
            sampler_name=args.method,
            source_type=args.source_type,
            module_path=args.module_path,
            config_path=args.config_path,
            config=config,
            max_samples=args.max_samples,
        )
    except SamplerTestError as exc:
        parser.error(str(exc))

    if args.format == "json":
        print(json.dumps(result_to_dict(result), indent=2, default=str))
    elif args.format == "yaml":
        print(format_yaml(result), end="")
    else:
        print(format_table(result))
    return 0


def sampler_config_from_args(args: argparse.Namespace) -> dict[str, Any]:
    return {
        key: value
        for key, value in {
            "n_samples": args.n_samples,
            "seed": args.seed,
            "skip": args.skip,
        }.items()
        if value is not None
    }


if __name__ == "__main__":
    raise SystemExit(main())

